build_from:
  aarch64: ghcr.io/hassio-addons/base-python/aarch64:11.0.1
  amd64: ghcr.io/hassio-addons/base-python/amd64:11.0.1
  armhf: ghcr.io/hassio-addons/base-python/armhf:11.0.1
  armv7: ghcr.io/hassio-addons/base-python/armv7:11.0.1
  i386: ghcr.io/hassio-addons/base-python/i386:11.0.1
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Asterisk"
  org.opencontainers.image.description: "PBX server for SIP devices like doorbells and phones."
  org.opencontainers.image.source: "https://github.com/TECH7Fox/Asterisk-add-on"
  org.opencontainers.image.licenses: "MIT"
