build_from:
  aarch64: ghcr.io/hassio-addons/base-python/aarch64:8.1.0
  amd64: ghcr.io/hassio-addons/base-python/amd64:8.1.0
  armhf: ghcr.io/hassio-addons/base-python/armhf:8.1.0
  armv7: ghcr.io/hassio-addons/base-python/armv7:8.1.0
  i386: ghcr.io/hassio-addons/base-python/i386:8.1.0
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Asterisk"
  org.opencontainers.image.description: "PBX server for SIP devices like doorbells and phones."
  org.opencontainers.image.source: "https://github.com/TECH7Fox/Asterisk-add-on"
  org.opencontainers.image.licenses: "MIT"
