name: Asterisk
version: 1.0.0
slug: asterisk
description: PBX server for SIP devices like doorbells and phones
url: https://github.com/TECH7Fox/Asterisk-add-on
image: "ghcr.io/tech7fox/{arch}-addon-asterisk"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant_api: true
map:
  - config:rw
  - ssl
options:
  ami_password: c32d3bd655d9226ffc062751ab9d1058
  video_support: true
  auto_add: true
  auto_add_secret: 1234abcd
  certfile: fullchain.pem
  keyfile: privkey.pem
  mailbox: false
  mailbox_port: 12345
  mailbox_password: my_password
  mailbox_extension: '101'
  api_key: GOOGLE_API_KEY
schema:
  ami_password: password
  video_support: bool
  auto_add: bool
  auto_add_secret: password
  certfile: str
  keyfile: str
  mailbox: bool
  mailbox_port: port
  mailbox_password: password
  mailbox_extension: str
  api_key: password
host_network: true
