name: Asterisk
version: 0.3.2
slug: asterisk
description: PBX server for SIP devices like doorbells and phones
url: https://github.com/TECH7Fox/Asterisk-add-on
image: "ghcr.io/tech7fox/{arch}-addon-asterisk"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant_api: true
stage: experimental
map:
  - config:rw
  - ssl
options:
  ami_password: c32d3bd655d9226ffc062751ab9d1058
  video_support: false
  auto_add: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ami_password: password
  video_support: bool
  auto_add: bool
  certfile: str
  keyfile: str
host_network: true
